<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBook-Pro16" failures="4" tests="4" name="Test" time="42.31" errors="0" timestamp="2024-08-22T15:50:10 EDT">
  <testcase classname="GoRest_ApiChaining.deleteUser" name="deleteUser_test" time="0.013">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at GoRest_ApiChaining.deleteUser.deleteUser_test(deleteUser.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser_test -->
  <testcase classname="GoRest_ApiChaining.CreateUser" name="createUser_test" time="42.197">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:237)
at GoRest_ApiChaining.CreateUser.createUser_test(CreateUser.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 33 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- createUser_test -->
  <testcase classname="GoRest_ApiChaining.updateUser" name="updateUser_test" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at GoRest_ApiChaining.updateUser.updateUser_test(updateUser.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- updateUser_test -->
  <testcase classname="GoRest_ApiChaining.getUser" name="getUser_test" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at GoRest_ApiChaining.getUser.getUser_test(getUser.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- getUser_test -->
</testsuite> <!-- Test -->
